// PARTY ACTIONS
export const SET_PLAYER_CHARACTER = "PARTY_SET_PLAYER_CHARACTER";
export const SET_PLAYER_NAME = "PARTY_SET_PLAYER_NAME";
export const SET_PLAYER_CUSTOMIZATION = "PARTY_SET_PLAYER_CUSTOMIZATION";